/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnItemType".
 */
export type ColumnItemType =
  | {
      blocks?:
        | (
            | AccordionBlockNestedType
            | CtaSectionBlockNestedType
            | StatsBlockNestedType
            | GalleryBlockNestedType
            | VideoBlockNestedType
            | SpacerBlockNestedType
            | ContactFormBlockNestedType
            | BannerBlockNestedType
            | FAQBlockNestedType
          )[]
        | null;
      settings?: ColumnSettingsType;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    members: MemberAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {
    richText: RichTextBlockType;
    accordion: AccordionBlockType;
    accordionNested: AccordionBlockNestedType;
    articleListing: ArticleListingBlockType;
    hero: HeroBlockType;
    features: FeaturesBlockType;
    ctaSection: CtaSectionBlockType;
    ctaSectionNested: CtaSectionBlockNestedType;
    stats: StatsBlockType;
    statsNested: StatsBlockNestedType;
    testimonials: TestimonialsBlockType;
    logoCloud: LogoCloudBlockType;
    twoColumn: TwoColumnBlockType;
    gallery: GalleryBlockType;
    galleryNested: GalleryBlockNestedType;
    video: VideoBlockType;
    videoNested: VideoBlockNestedType;
    team: TeamBlockType;
    marquee: MarqueeBlockType;
    spacer: SpacerBlockType;
    spacerNested: SpacerBlockNestedType;
    contactForm: ContactFormBlockType;
    contactFormNested: ContactFormBlockNestedType;
    pricing: PricingBlockType;
    banner: BannerBlockType;
    bannerNested: BannerBlockNestedType;
    faq: FAQBlockType;
    faqNested: FAQBlockNestedType;
    columns: ColumnsBlockType;
    icon: IconBlockType;
    callToAction: CallToActionBlockType;
  };
  collections: {
    articles: Article;
    media: Media;
    pages: Page;
    members: Member;
    users: User;
    'invitation-codes': InvitationCode;
    tags: Tag;
    cases: Case;
    appointments: Appointment;
    'case-intakes': CaseIntake;
    heirs: Heir;
    assets: Asset;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'invitation-codes': InvitationCodesSelect<false> | InvitationCodesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    'case-intakes': CaseIntakesSelect<false> | CaseIntakesSelect<true>;
    heirs: HeirsSelect<false> | HeirsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    footer: FooterSettings;
    'general-settings': GeneralSettings;
    header: HeaderSettings;
    'seo-settings': SEOSettings;
    invitations: Invitation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Member | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockType".
 */
export interface RichTextBlockType {
  data?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('section' | 'div') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockType".
 */
export interface AccordionBlockType {
  items?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    accordionType?: ('single' | 'multiple') | null;
    width?: ResponsiveGroupType;
    alignment?: ('left' | 'center' | 'right') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * Maximum width constraint for the accordion
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResponsiveGroupType".
 */
export interface ResponsiveGroupType {
  type?: ('preset' | 'custom') | null;
  preset?: ResponsiveSelectType;
  custom?: ResponsiveNumberType;
}
/**
 * Select predefined size values per breakpoint
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResponsiveSelectType".
 */
export interface ResponsiveSelectType {
  base?: ('xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'fullwidth') | null;
  xs?: ('' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'fullwidth') | null;
  sm?: ('' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'fullwidth') | null;
  md?: ('' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'fullwidth') | null;
  lg?: ('' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'fullwidth') | null;
  xl?: ('' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'fullwidth') | null;
}
/**
 * Enter custom pixel values per breakpoint (px)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResponsiveNumberType".
 */
export interface ResponsiveNumberType {
  base?: number | null;
  xs?: number | null;
  sm?: number | null;
  md?: number | null;
  lg?: number | null;
  xl?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockNestedType".
 */
export interface AccordionBlockNestedType {
  items?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    accordionType?: ('single' | 'multiple') | null;
    alignment?: ('left' | 'center' | 'right') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordionNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleListingBlockType".
 */
export interface ArticleListingBlockType {
  tags?: (string | Tag)[] | null;
  limit?: number | null;
  columns?: ('1' | '2' | '3' | '4') | null;
  sort?: ('-publishedDate' | 'publishedDate' | 'title' | '-title') | null;
  showPagination?: boolean | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'articleListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  generateSlug?: boolean | null;
  slug: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockType".
 */
export interface HeroBlockType {
  heading: string;
  subheading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: LinkProps;
        id?: string | null;
      }[]
    | null;
  media?: (string | null) | Media;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    layout?: ('contentLeft' | 'contentRight' | 'contentCenter' | 'overlay' | 'fullOverlay') | null;
    heroHeight?: ('default' | 'medium' | 'full') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkProps".
 */
export interface LinkProps {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null);
  url?: string | null;
  label: string;
  appearance?: ('default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link') | null;
  size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  isHome?: boolean | null;
  generateSlug?: boolean | null;
  slug: string;
  pathname?: string | null;
  type?: ('standard' | 'dynamic') | null;
  dynamicCollection?: 'articles' | null;
  blocks?:
    | (
        | RichTextBlockType
        | AccordionBlockType
        | ArticleListingBlockType
        | HeroBlockType
        | FeaturesBlockType
        | CtaSectionBlockType
        | StatsBlockType
        | TestimonialsBlockType
        | LogoCloudBlockType
        | TwoColumnBlockType
        | GalleryBlockType
        | VideoBlockType
        | TeamBlockType
        | MarqueeBlockType
        | SpacerBlockType
        | ContactFormBlockType
        | PricingBlockType
        | BannerBlockType
        | FAQBlockType
        | ColumnsBlockType
      )[]
    | null;
  beforeList?:
    | (
        | RichTextBlockType
        | AccordionBlockType
        | ArticleListingBlockType
        | HeroBlockType
        | FeaturesBlockType
        | CtaSectionBlockType
        | StatsBlockType
        | TestimonialsBlockType
        | LogoCloudBlockType
        | TwoColumnBlockType
        | GalleryBlockType
        | VideoBlockType
        | TeamBlockType
        | MarqueeBlockType
        | SpacerBlockType
        | ContactFormBlockType
        | PricingBlockType
        | BannerBlockType
        | FAQBlockType
        | ColumnsBlockType
      )[]
    | null;
  afterList?:
    | (
        | RichTextBlockType
        | AccordionBlockType
        | ArticleListingBlockType
        | HeroBlockType
        | FeaturesBlockType
        | CtaSectionBlockType
        | StatsBlockType
        | TestimonialsBlockType
        | LogoCloudBlockType
        | TwoColumnBlockType
        | GalleryBlockType
        | VideoBlockType
        | TeamBlockType
        | MarqueeBlockType
        | SpacerBlockType
        | ContactFormBlockType
        | PricingBlockType
        | BannerBlockType
        | FAQBlockType
        | ColumnsBlockType
      )[]
    | null;
  settings?: {
    /**
     * Define which articles to display.
     */
    query?: {
      where?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      sort?: string[] | null;
    };
  };
  parent?: (string | null) | Page;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlockType".
 */
export interface FeaturesBlockType {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        icon?: string | null;
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    layout?: ('grid' | 'list') | null;
    columns?: ('2' | '3' | '4') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaSectionBlockType".
 */
export interface CtaSectionBlockType {
  heading: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: LinkProps;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    background?: ('default' | 'muted' | 'primary') | null;
    alignment?: ('left' | 'center') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockType".
 */
export interface StatsBlockType {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        value: string;
        label: string;
        prefix?: string | null;
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    layout?: ('grid' | 'inline') | null;
    columns?: ('2' | '3' | '4') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockType".
 */
export interface TestimonialsBlockType {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        quote: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        authorName: string;
        authorRole?: string | null;
        authorCompany?: string | null;
        authorAvatar?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    layout?: ('grid' | 'carousel' | 'single') | null;
    columns?: ('2' | '3') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  credit?: string[] | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlockType".
 */
export interface LogoCloudBlockType {
  heading?: string | null;
  subheading?: string | null;
  logos?:
    | {
        image: string | Media;
        name: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    layout?: ('grid' | 'marquee') | null;
    columns?: ('3' | '4' | '5' | '6') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlockType".
 */
export interface TwoColumnBlockType {
  heading?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  media?: (string | null) | Media;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    mediaPosition?: ('left' | 'right') | null;
    verticalAlignment?: ('top' | 'center' | 'bottom') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColumn';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlockType".
 */
export interface GalleryBlockType {
  heading?: string | null;
  subheading?: string | null;
  images?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    layout?: ('grid' | 'masonry') | null;
    columns?: ('2' | '3' | '4') | null;
    lightbox?: boolean | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlockType".
 */
export interface VideoBlockType {
  heading?: string | null;
  url: string;
  poster?: (string | null) | Media;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    aspectRatio?: ('16/9' | '4/3' | '1/1') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlockType".
 */
export interface TeamBlockType {
  heading?: string | null;
  subheading?: string | null;
  members?:
    | {
        name: string;
        role?: string | null;
        bio?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        photo?: (string | null) | Media;
        socialLinks?:
          | {
              platform: 'linkedin' | 'twitter' | 'github' | 'instagram' | 'website';
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    columns?: ('2' | '3' | '4') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlockType".
 */
export interface MarqueeBlockType {
  items?:
    | {
        type: 'text' | 'image';
        text?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    speed?: ('slow' | 'normal' | 'fast') | null;
    direction?: ('ltr' | 'rtl') | null;
    pauseOnHover?: boolean | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlockType".
 */
export interface SpacerBlockType {
  height: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlockType".
 */
export interface ContactFormBlockType {
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  fields?:
    | {
        name: string;
        fieldType: 'text' | 'email' | 'tel' | 'textarea' | 'select';
        required?: boolean | null;
        placeholder?: string | null;
        options?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  submitLabel?: string | null;
  successMessage?: string | null;
  endpoint?: string | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlockType".
 */
export interface PricingBlockType {
  heading?: string | null;
  subheading?: string | null;
  plans?:
    | {
        name: string;
        price: string;
        period?: ('monthly' | 'yearly' | 'one-time') | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        highlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    columns?: ('2' | '3' | '4') | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlockType".
 */
export interface BannerBlockType {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    type?: ('info' | 'warning' | 'success') | null;
    dismissible?: boolean | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockType".
 */
export interface FAQBlockType {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    allowMultiple?: boolean | null;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlockType".
 */
export interface ColumnsBlockType {
  prefix?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  suffix?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  columns?: ColumnItemType;
  design?: {
    spacing?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    spacingType?: ('margin' | 'padding') | null;
    gap?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    verticalAlignment?: ('start' | 'center' | 'end' | 'stretch') | null;
    advancedColumnSettings?: boolean | null;
    alignSelf?: ('auto' | 'start' | 'center' | 'end' | 'stretch') | null;
    width?: ColumnWidthType;
  };
  settings?: {
    id?: string | null;
    htmlTag?: ('div' | 'section' | 'article') | null;
    containerType?: ('none' | 'default' | 'post') | null;
    withPrefix?: boolean | null;
    withSuffix?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'columns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaSectionBlockNestedType".
 */
export interface CtaSectionBlockNestedType {
  heading: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: LinkProps;
        id?: string | null;
      }[]
    | null;
  design?: {
    background?: ('default' | 'muted' | 'primary') | null;
    alignment?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaSectionNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockNestedType".
 */
export interface StatsBlockNestedType {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        value: string;
        label: string;
        prefix?: string | null;
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    layout?: ('grid' | 'inline') | null;
    columns?: ('2' | '3' | '4') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlockNestedType".
 */
export interface GalleryBlockNestedType {
  heading?: string | null;
  subheading?: string | null;
  images?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  design?: {
    layout?: ('grid' | 'masonry') | null;
    columns?: ('2' | '3' | '4') | null;
    lightbox?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlockNestedType".
 */
export interface VideoBlockNestedType {
  heading?: string | null;
  url: string;
  poster?: (string | null) | Media;
  design?: {
    aspectRatio?: ('16/9' | '4/3' | '1/1') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlockNestedType".
 */
export interface SpacerBlockNestedType {
  height: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacerNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlockNestedType".
 */
export interface ContactFormBlockNestedType {
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  fields?:
    | {
        name: string;
        fieldType: 'text' | 'email' | 'tel' | 'textarea' | 'select';
        required?: boolean | null;
        placeholder?: string | null;
        options?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  submitLabel?: string | null;
  successMessage?: string | null;
  endpoint?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactFormNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlockNestedType".
 */
export interface BannerBlockNestedType {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  design?: {
    type?: ('info' | 'warning' | 'success') | null;
    dismissible?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'bannerNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockNestedType".
 */
export interface FAQBlockNestedType {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  design?: {
    allowMultiple?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqNested';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnSettingsType".
 */
export interface ColumnSettingsType {
  alignSelf?: ('auto' | 'start' | 'center' | 'end' | 'stretch') | null;
  width?: ColumnWidthType;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnWidthType".
 */
export interface ColumnWidthType {
  base?: ('' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  xs?: ('' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  sm?: ('' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  md?: ('' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  lg?: ('' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
  xl?: ('' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  generateSlug?: boolean | null;
  slug: string;
  publishedDate?: string | null;
  authors?: (string | User)[] | null;
  tags?: (string | Tag)[] | null;
  pathname?: string | null;
  title: string;
  excerpt?: string | null;
  featuredImage?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  name?: string | null;
  roles?: ('admin' | 'editor' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconBlockType".
 */
export interface IconBlockType {
  icon?: string | null;
  color?: string | null;
  size?: {
    mobile?: number | null;
    tablet?: number | null;
    desktop?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'icon';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlockType".
 */
export interface CallToActionBlockType {
  links?:
    | {
        link: LinkProps;
        id?: string | null;
      }[]
    | null;
  design?: {
    marginTop?: {
      mobile?: number | null;
      tablet?: number | null;
      desktop?: number | null;
    };
    marginBottom?: {
      mobile?: number | null;
      tablet?: number | null;
      desktop?: number | null;
    };
    align?: {
      mobile?: ('none' | 'left' | 'center' | 'right' | 'fullWidth') | null;
      tablet?: ('none' | 'left' | 'center' | 'right' | 'fullWidth') | null;
      desktop?: ('none' | 'left' | 'center' | 'right' | 'fullWidth') | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  firstName: string;
  secondName?: string | null;
  lastName: string;
  secondLastName?: string | null;
  /**
   * The user's preferred language for emails and system notifications.
   */
  preferredLocale: 'es' | 'en';
  role: 'cliente' | 'abogado';
  /**
   * Inactive lawyers are redirected to a pending-activation page on login. Takes effect on next login.
   */
  isActive?: boolean | null;
  /**
   * Solo dígitos, sin puntos. Ejemplo: 1012345678
   */
  cedula?: string | null;
  /**
   * Número móvil colombiano. Ejemplo: 3001234567
   */
  telefono?: string | null;
  ciudad?: string | null;
  /**
   * Crédito acumulado en pesos COP. Gestionado automáticamente por el hook autorizarCredito. Solo editable por Admin directamente; los abogados deben usar el campo autorizarCredito en Citas.
   */
  creditoAcumulado?: number | null;
  isVerified?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitation-codes".
 */
export interface InvitationCode {
  id: string;
  code?: string | null;
  status?: ('available' | 'used') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: string;
  /**
   * Generado automáticamente al crear el caso.
   */
  caseNumber?: string | null;
  status?: ('active' | 'completed') | null;
  currentPhase?: number | null;
  tier: 'estandar' | 'premium' | 'elite';
  responsable?: (string | null) | Member;
  abogadoAsignado?: (string | null) | Member;
  /**
   * Cédula del cliente invitado (solo cuando el abogado crea el caso). Sin puntos.
   */
  invitacionCedula?: string | null;
  /**
   * Estado de la invitación cuando el caso fue creado por el abogado.
   */
  invitacionStatus?: ('pendiente_aceptacion' | 'aceptada') | null;
  /**
   * Se copia del Intake.
   */
  tieneTestamento?: boolean | null;
  /**
   * Se copia del Intake.
   */
  acuerdoHerederos?: ('si' | 'no_sabe') | null;
  causante?: {
    nombre?: string | null;
    cedula?: string | null;
    fechaFallecimiento?: string | null;
    ciudadFallecimiento?: string | null;
  };
  /**
   * El formulario de intake que originó este caso.
   */
  caseIntake?: (string | null) | CaseIntake;
  /**
   * Consulta previa si el cliente tuvo una antes de abrir el caso.
   */
  appointment?: (string | null) | Appointment;
  /**
   * Solo visible para abogados y administradores.
   */
  notasInternas?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Visible para el cliente en su dashboard.
   */
  notasAlCliente?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-intakes".
 */
export interface CaseIntake {
  id: string;
  member: string | Member;
  status?: ('draft' | 'submitted' | 'paid') | null;
  tierElegido?: ('estandar' | 'premium' | 'elite') | null;
  tieneTestamento?: boolean | null;
  acuerdoHerederos: 'si' | 'no_sabe';
  causanteNombre: string;
  causanteCedula: string;
  causanteFechaFallecimiento: string;
  causanteCiudadFallecimiento: string;
  bienesDescripcion?: string | null;
  parentescoConCausante?: ('hijo' | 'hermano' | 'conyuge' | 'nieto' | 'sobrino' | 'padre_madre' | 'otro') | null;
  /**
   * Cita previa si el cliente tuvo una antes de abrir el caso.
   */
  appointment?: (string | null) | Appointment;
  /**
   * ID de transacción Wompi. Se llena en RFC-008.
   */
  wompiTransactionId?: string | null;
  /**
   * Monto total pagado en COP. Se llena en RFC-008.
   */
  montoTotal?: number | null;
  herederosEstimados: number;
  valorEstimadoTotal?: number | null;
  /**
   * Se llena automáticamente al confirmar el pago.
   */
  case?: (string | null) | Case;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  member: string | Member;
  tipo:
    | 'consulta_virtual'
    | 'consulta_presencial'
    | 'mediacion_virtual'
    | 'mediacion_presencial'
    | 'caso_virtual'
    | 'caso_presencial';
  monto: number;
  status?: ('pendiente_pago' | 'pagada' | 'realizada' | 'cancelada') | null;
  /**
   * Solo Paola puede activar esta casilla. Suma el monto al crédito del cliente cuando el estado sea "Realizada".
   */
  autorizarCredito?: boolean | null;
  /**
   * Gestionado automáticamente por el hook. No editar manualmente.
   */
  creditoApplied?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heirs".
 */
export interface Heir {
  id: string;
  case: string | Case;
  nombre: string;
  cedula: string;
  parentesco: 'hijo' | 'conyuge' | 'padre' | 'hermano' | 'otro';
  esFallecido?: boolean | null;
  esRepresentante?: boolean | null;
  herederoOriginal?: (string | null) | Heir;
  /**
   * Solo abogados o administradores pueden validar la representación.
   */
  representacionValidada?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  case: string | Case;
  tipo: 'inmueble' | 'vehiculo' | 'cuenta' | 'accion' | 'otro';
  valorEstimado: number;
  descripcion: string;
  identificador: string;
  investigacion?: {
    resultado?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'invitation-codes';
        value: string | InvitationCode;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'cases';
        value: string | Case;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'case-intakes';
        value: string | CaseIntake;
      } | null)
    | ({
        relationTo: 'heirs';
        value: string | Heir;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'members';
        value: string | Member;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'members';
        value: string | Member;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  publishedDate?: T;
  authors?: T;
  tags?: T;
  pathname?: T;
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  isHome?: T;
  generateSlug?: T;
  slug?: T;
  pathname?: T;
  type?: T;
  dynamicCollection?: T;
  blocks?: T | {};
  beforeList?: T | {};
  afterList?: T | {};
  settings?:
    | T
    | {
        query?:
          | T
          | {
              where?: T;
              sort?: T;
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  firstName?: T;
  secondName?: T;
  lastName?: T;
  secondLastName?: T;
  preferredLocale?: T;
  role?: T;
  isActive?: T;
  cedula?: T;
  telefono?: T;
  ciudad?: T;
  creditoAcumulado?: T;
  isVerified?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitation-codes_select".
 */
export interface InvitationCodesSelect<T extends boolean = true> {
  code?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  caseNumber?: T;
  status?: T;
  currentPhase?: T;
  tier?: T;
  responsable?: T;
  abogadoAsignado?: T;
  invitacionCedula?: T;
  invitacionStatus?: T;
  tieneTestamento?: T;
  acuerdoHerederos?: T;
  causante?:
    | T
    | {
        nombre?: T;
        cedula?: T;
        fechaFallecimiento?: T;
        ciudadFallecimiento?: T;
      };
  caseIntake?: T;
  appointment?: T;
  notasInternas?: T;
  notasAlCliente?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  member?: T;
  tipo?: T;
  monto?: T;
  status?: T;
  autorizarCredito?: T;
  creditoApplied?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-intakes_select".
 */
export interface CaseIntakesSelect<T extends boolean = true> {
  member?: T;
  status?: T;
  tierElegido?: T;
  tieneTestamento?: T;
  acuerdoHerederos?: T;
  causanteNombre?: T;
  causanteCedula?: T;
  causanteFechaFallecimiento?: T;
  causanteCiudadFallecimiento?: T;
  bienesDescripcion?: T;
  parentescoConCausante?: T;
  appointment?: T;
  wompiTransactionId?: T;
  montoTotal?: T;
  herederosEstimados?: T;
  valorEstimadoTotal?: T;
  case?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heirs_select".
 */
export interface HeirsSelect<T extends boolean = true> {
  case?: T;
  nombre?: T;
  cedula?: T;
  parentesco?: T;
  esFallecido?: T;
  esRepresentante?: T;
  herederoOriginal?: T;
  representacionValidada?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  case?: T;
  tipo?: T;
  valorEstimado?: T;
  descripcion?: T;
  identificador?: T;
  investigacion?:
    | T
    | {
        resultado?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface FooterSettings {
  id: string;
  navigation?: {
    title?: string | null;
    links?:
      | {
          link: LinkProps;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    email?: string | null;
    phone?: string | null;
    socialLinks?:
      | {
          platform: 'facebook' | 'youtube' | 'x' | 'instagram' | 'linkedin' | 'mail';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  legal?: {
    /**
     * Registered legal name of the organization
     */
    legalName?: string | null;
    title?: string | null;
    links?:
      | {
          link: LinkProps;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSettings {
  id: string;
  typography?: {
    headingFont?:
      | (
          | 'Inter'
          | 'Roboto'
          | 'Open Sans'
          | 'Lato'
          | 'Montserrat'
          | 'Poppins'
          | 'Raleway'
          | 'Nunito'
          | 'Playfair Display'
          | 'Merriweather'
          | 'Source Sans 3'
          | 'PT Sans'
          | 'Noto Sans'
          | 'Ubuntu'
          | 'Rubik'
          | 'Work Sans'
          | 'DM Sans'
          | 'Libre Baskerville'
          | 'Crimson Text'
          | 'IBM Plex Sans'
          | 'IBM Plex Serif'
          | 'IBM Plex Mono'
          | 'Fira Sans'
          | 'Outfit'
          | 'Space Grotesk'
          | 'Manrope'
          | 'Plus Jakarta Sans'
          | 'Geist'
          | 'Geist Mono'
          | 'JetBrains Mono'
        )
      | null;
    bodyFont?:
      | (
          | 'Inter'
          | 'Roboto'
          | 'Open Sans'
          | 'Lato'
          | 'Montserrat'
          | 'Poppins'
          | 'Raleway'
          | 'Nunito'
          | 'Playfair Display'
          | 'Merriweather'
          | 'Source Sans 3'
          | 'PT Sans'
          | 'Noto Sans'
          | 'Ubuntu'
          | 'Rubik'
          | 'Work Sans'
          | 'DM Sans'
          | 'Libre Baskerville'
          | 'Crimson Text'
          | 'IBM Plex Sans'
          | 'IBM Plex Serif'
          | 'IBM Plex Mono'
          | 'Fira Sans'
          | 'Outfit'
          | 'Space Grotesk'
          | 'Manrope'
          | 'Plus Jakarta Sans'
          | 'Geist'
          | 'Geist Mono'
          | 'JetBrains Mono'
        )
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface HeaderSettings {
  id: string;
  navLinks?:
    | {
        link: LinkProps;
        id?: string | null;
      }[]
    | null;
  logo?: {
    type?: ('none' | 'image' | 'text') | null;
    image?: (string | null) | Media;
    text?: string | null;
  };
  cta?: {
    enabled?: boolean | null;
    link?: LinkProps;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SEOSettings {
  id: string;
  /**
   * The name of your website
   */
  siteName?: string | null;
  /**
   * A short description of your website
   */
  tagline?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: string;
  title: string;
  subtitle: string;
  mockPhrase: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Cover image displayed on the left side of the login page. Recommended: portrait or square, min 1200px tall.
   */
  loginCoverImage?: (string | null) | Media;
  /**
   * Enable bilingual routing and the frontend Language Switcher.
   */
  enableMultiLanguage: boolean;
  /**
   * The default language for new visitors.
   */
  defaultLanguage: 'en' | 'es';
  /**
   * The languages currently active on the site.
   */
  supportedLanguages: ('en' | 'es')[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?: T | LinkPropsSelect<T>;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        email?: T;
        phone?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  legal?:
    | T
    | {
        legalName?: T;
        title?: T;
        links?:
          | T
          | {
              link?: T | LinkPropsSelect<T>;
              id?: T;
            };
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkProps_select".
 */
export interface LinkPropsSelect<T extends boolean = true> {
  type?: T;
  newTab?: T;
  reference?: T;
  url?: T;
  label?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  typography?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        link?: T | LinkPropsSelect<T>;
        id?: T;
      };
  logo?:
    | T
    | {
        type?: T;
        image?: T;
        text?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        link?: T | LinkPropsSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  mockPhrase?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  loginCoverImage?: T;
  enableMultiLanguage?: T;
  defaultLanguage?: T;
  supportedLanguages?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}