/** Generated by generate:translations. Do not edit. 
Regenerate with `pnpm run generate:translations`. */
import { en } from './en'
import { es } from './es'

export { en }
export { es }

export const translations = {
  en,
  es,
}
